server:
  port: 8081
spring:
#  application:
#    #    服务名称
#    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/day01_springcloud01?useSSL=false
    username: root
    password: 1026
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      # nacos服务器地址
#      server-addr: localhost:8848
#      discovery:
#        # 集群名称 CD代指成都 SH代指上海
#        cluster-name: SH
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# 定义eureka客户端访问路径
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:2333/eureka

pattern:
  name: 本地环境local