server:
  port: 8080
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/day01_springcloud01?useSSL=false
    username: root
    password: 1026
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:81
      discovery:
        # 集群名称 CD代指成都
#        cluster-name: CD
#        namespace: 8d640f60-91a6-4bc7-8873-44a8a95a6e58
        # 配置实例为临时true/非临时false
        ephemeral: true
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# 定义eureka客户端访问路径
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:2333/eureka
# 要做配置的微服务名称
userservice:
  ribbon:
    # 配置eureka的ribbon的负载均衡load balance规则
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 配置nacos的负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 指定对哪个服务
    clients: userservice
feign:
  httpclient:
    # 支持HttpClient连接池
    enabled: true
    connection-timeout: 2000
    connection-timer-repeat: 3000
    # 最大连接数
    max-connections: 200
    # 单个路径的最大连接数
    max-connections-per-route: 50
#  client:
#    config:
#      # 可指定服务名称，default代表全局生效
#      default:
#        # feign日志输出级别设置 FULL代表全部日志信息
#        loggerLevel: FULL
  # 配置feign的默认连接工具为Apache HttpClient